WebApplication11/Controllers/ProductUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication11.Data;
using WebApplication11.Models;
using WebApplication11.Repository;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;

namespace WebApplication11.Controllers
{

    public class ProductUserController : Controller

    {

        IHttpContextAccessor _httpContextAccessor;
        private readonly DatabaseContaxt _context;
        private readonly IWebHostEnvironment webHostEnvironment;
        public IProductUserViewModel _ProductUserRepository;
        public ProductUserController(DatabaseContaxt context, IWebHostEnvironment hostEnvironment, IProductUserViewModel productUserRepository, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;

            webHostEnvironment = hostEnvironment;
            _ProductUserRepository = productUserRepository;
            _httpContextAccessor = httpContextAccessor;
        }





        // GET: ProductModels
        public async Task<IActionResult> Index()
        {
            string cookie = _httpContextAccessor.HttpContext.Request.Cookies["key"];
            CookieOptions option = new CookieOptions();
            if (cookie == null)
            {
                Guid abc = Guid.NewGuid();
                var value = Set("key", abc.ToString(), 2);
            }
            //else
            //{
            //    if (!isset($_COOKIE['key']))
            //    {
            //        DeleteId(cookie);
            //        exit;
            //    }
            //}
            return View(await _context.ProductModels.ToListAsync());
        }
        public string Set(string key, string value, int? expireTime)
        {
            CookieOptions option = new CookieOptions();

            option.Expires = DateTime.Now.AddDays(expireTime.Value);

            Response.Cookies.Append(key, value, option);
            return value;
        }
        public void Remove(string key)
        {
            Response.Cookies.Delete(key);
        }
        // Detail
        public async Task<IActionResult> Details(int? id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var productdetails = await _ProductUserRepository.ProductDetails(id);
            if (productdetails == null)
            {
                return NotFound();
            }
            return View(productdetails);
        }
        // Delete product from cart
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {

            var productdelete = await _ProductUserRepository.Del(id);
            //   return View(productdelete);
            return RedirectToAction(nameof(GetCart));
        }
       
        public async Task<IActionResult> EmptyCart(string id)
        {
            var productModel = await _ProductUserRepository.DeleteAll();
            return RedirectToAction(nameof(GetCart));
        }

        // getCart
        public async Task<IActionResult> GetCart(int id)
        {
            string cookieValueFromContext = _httpContextAccessor.HttpContext.Request.Cookies["key"];
            var products = await _ProductUserRepository.getcartItems(id);
             ViewBag.list = products.Count;
           // ViewBag.list = 0;
            ViewBag.messaage = cookieValueFromContext;
            return View(products);

        }
        // add Cart
        public async Task<IActionResult> DetailsSending(int id)
        {
            var Add = await _ProductUserRepository.AddCart(id);
            if (id == null)
            {
                return NotFound();
            }
            return RedirectToAction(nameof(GetCart));
        }
        public async Task DeleteId(string id)
        {
            var clearCart = await _context.Carts.Where(x => x.UserId == id).FirstOrDefaultAsync();
            _context.Carts.Remove(clearCart);
            await _context.SaveChangesAsync();
        }

    }
}

WebApplication11/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication11</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/solar.css" asp-append-version="true" />

</head>
<body>
    <header>




        <nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="ProductUser" asp-action="Index">
                    <i class="bi bi-apple me-2"></i>
                    SoftwareCraft
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor02">
                    @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="ListRoles">Manage Roles</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-controller="Account" asp-action="Register">Register New User</a>
                            </li>
                        </ul>
                    }
                    else if (signInManager.IsSignedIn(User) && User.IsInRole("Operator"))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="ProductAdmin" asp-action="Index">Dasboard</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>

                        </ul>
                    }

                    else if (signInManager.IsSignedIn(User) && User.IsInRole("User"))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li>
                                <a class="nav-link" asp-controller="ProductUser" asp-action="GetCart">
                                    <i class="bi bi-cart3"></i>
                                    Cart
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>

                        </ul>
                    }
                    else
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li>
                                <a class="nav-link" asp-controller="ProductUser" asp-action="GetCart">
                                    <i class="bi bi-cart3"></i>
                                    Cart
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                            @*  <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                                </li>*@
                        </ul>
                    }
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="text" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class=" footer text-muted">
        <div class="container">
            &copy; 2022 - WebApplication11 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>